name: Python Tests with Coverage

on:
  push:
      branches: [ "*" ]
  pull_request:
      branches:
        - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        make install-requirements
        
    - name: Run tests with coverage
      run: |
        make test-coverage
